### ISSUE TITLE
Via Stackoverflow: npzread(filename.npz) very slow

### ISSUE THREAD

**Issue by mschauer** [fhs/NPZ.jl#19] opened 2017-09-11 06:48 UTC
Timings degrade critically when `.npz` contains several variables, see https://stackoverflow.com/questions/46116346/julia-npzreadfilename-npz-very-slow . In

Possibly because of https://github.com/fhs/NPZ.jl/blob/master/src/NPZ.jl#L197

**Comment by standarddeviant** [comment] 2018-10-08 18:27
I can confirm that this issue is still relevant
```julia
julia> @time load_xy();
122.734489 seconds (26.65 M allocations: 1006.223 MiB, 0.11% gc time)

julia> @time load_x_and_y();
  0.015817 seconds (5.03 k allocations: 9.844 MiB)
```

I've been using `MAT.jl` for a project and want to switch over to using `NPZ.jl` for a few reasons, but this is a show-stopper for me.  I'll see if I can deduce what's taking the most time. It could be an issue with ZipFile.Reader.

**Comment by bhalonen** [comment] 2018-10-25 21:50
@standarddeviant and @mschauer  My pull request should minimize the issue.

**Comment by fhs** [comment] 2019-01-04 18:30
Closing due to <https://github.com/fhs/ZipFile.jl/pull/49>.
Reopen if it's still an issue.

**Closed by fhs** 2019-01-04 18:30 UTC
